### ISSUE TITLE
회원가입 API 구축

### ISSUE THREAD

**Issue by Moon-GD** [softeerbootcamp/Team6#17]
- [x] 회원 entity 생성
- [x] Session을 사용하여 redis에 저장
- [x] 회원가입 컨트롤러
- [x] 인증 로직 생성 및 테스트
- [x] 세션 redis저장 테스트

![Image](https://user-images.githubusercontent.com/87477702/216237024-76932b66-ac73-4b41-8f01-576703f5b28d.png)
해당 명세를 참고하여 개발

**Comment by gyuturn** [comment]
https://www.notion.so/API-9f0f154f923341749dfce02ee37f1cf0?p=183d718347744c87b191dca696095e0b&pm=s 
참고
