### ISSUE TITLE
메인 화면 뷰 작성

### ISSUE THREAD

**Issue by gyuturn** [softeerbootcamp/Team6#6]
- [  ] 근처 주유소 탐색 버튼 연결
- [  ] 선택지형 채팅 봇
- [  ] 페이지 사용 설명서 페이드 인 / 아웃
- [  ] 로그인 페이지 연결
- [  ] 마이 페이지 연결

**Comment by jaewonjjang** [comment]
추후에 이벤트, 애니메이션 추가하면 좋을것 같습니다. 확인했습니다.

**Comment by Moon-GD** [comment]
선택지형 채팅 봇은 다른 issue로 분리하였습니다.
